spring.application.name=lmsBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/Library_Management_System
spring.datasource.username=postgres
spring.datasource.password=Harshal@2003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
